services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: paysync
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - paysync-network

  app:
    image: rodkrtz/paysync:latest
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/paysync
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - paysync-network

networks:
  paysync-network:
    driver: bridge